### ISSUE TITLE
Please increment the version number and publish a new version to npm

### ISSUE THREAD

**Issue by midnightcodr** [msfidelis/rsmq-promise#3]
Hi,
Saw an update was made (added `quit()`) method which is nice. However I am not able to get the updated code by simply doing a `npm install rsmq-promise`. Removing the existing one and re-installing doesn't work either. It seems that you forgot to up the version number and publish a new version to npm.

**Comment by msfidelis** [comment]
Hi @midnightcodr! The version `v1.0.2` has released with `quit()` method! Thanks for remember this!

**Comment by midnightcodr** [comment]
@msfidelis thanks but seems version 1.0.2 is still not yet published to npm. I just checked https://www.npmjs.com/package/rsmq-promise

**Comment by msfidelis** [comment]
I'm sorry. This is my fault. It's just published now. Thanks a lot! 👍

**Comment by midnightcodr** [comment]
Awesome. Just tested working. Thank you @msfidelis
