### ISSUE TITLE
Version of rsmq included does not support realtime feature

### ISSUE THREAD

**Issue by jextrevor** [msfidelis/rsmq-promise#4]
The version of rsmq included (0.8.2) is out of date. Newer versions of rsmq include features such as realtime pub/sub when a message is sent and typescript typings. rsmq-promise ought to update its version of rsmq to support features such as these.

**Comment by overflowz** [comment]
bump on this.

**Comment by mo-advisa** [comment]
true, I have to wrap the new rsmq in my own promises to be able to use realtime feature.

**Comment by msfidelis** [comment]
I updated de rsmq dependency to latest version and published rsmq-promise to version `1.0.3` to support this.
